language: python

matrix:
  include:
#    - python: 2.6
#      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37

before_install:
# install WCPG library
    - ./autogen.sh && ./configure && make -j&& sudo make install;
# install required python packages for build and coverage
    - pip install pytest pytest-cov
    - pip install coveralls

install:
    - pip install tox

script:
    - tox

notifications:
email: false

after_success:
    - if [[ $TOXENV == py36 ]]; then
          coveralls;
      fi
