language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

cache: pip

matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"
      osx_image: xcode7.3

before_install:
  # update apt-get or install python 3.6
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get -qq update || travis_terminate 1;
      pip install --upgrade setuptools;
    else
      alias pip="pip3";
      brew update;
      brew upgrade python;
      PATH=/usr/local/opt/bison/bin:/usr/local/opt/python/libexec/bin:$PATH;
    fi

install:
  # install the prerequisites
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install f2c || travis_terminate 1;
      sudo apt-get install libmpfr-dev || travis_terminate 1;
      sudo apt-get install libmpfi-dev || travis_terminate 1;
      sudo apt-get build-dep python-scipy || travis_terminate 1;
    else
      brew install mpfi;
      pip install numpy;
      brew install gcc || brew link --overwrite gcc;
      brew tap homebrew/boneyard;
      wget https://gist.github.com/thilaire/e9ec0af8432408c6f2499d20c17aca3b/raw -O buildf2c;
      sh buildf2c;
    fi
  # install WCPG library
  - sh autogen.sh && ./configure && make -j&& sudo make install;
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib;
  # install required python packages for build and coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install 'urllib3==1.22' --force-reinstall
  # and then install WCPG wrapper
  - python setup.py  install

script:
    - pytest --cov=fixif.WCPG -s

notifications:
email: false

after_success:
    # run coveralls for Python 3.6 under linux with Sollya and Slycot installed
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6"  && "$TRAVIS_OS_NAME" == "linux" ]]; then
          coveralls;
      fi
