language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

cache: pip

matrix:
  include:
    - os: osx
      language: generic
      python: "3.6"

before_install:
  # update apt-get or install python 3.6
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get -qq update || travis_terminate 1;
      pip install --upgrade setuptools;
    else
      brew update || travis_terminate 1;
      brew upgrade python || travis_terminate 1;
      PATH=/usr/local/opt/bison/bin:/usr/local/opt/python/libexec/bin:$PATH || travis_terminate 1;
    fi

install:
  # install the prerequisites
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install f2c || travis_terminate 1;
      sudo apt-get install libmpfr-dev || travis_terminate 1;
      sudo apt-get install libmpfi-dev || travis_terminate 1;
      sudo apt-get build-dep python-scipy || travis_terminate 1;
    else
      brew install mpfi || travis_terminate 1;
      pip install numpy || travis_terminate 1;
      brew install gcc || brew link --overwrite gcc;
      brew install f2c || travis_terminate 1;
    fi
  # install WCPG library
  - sh autogen.sh && ./configure && make -j&& sudo make install;
  - LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH;
  # install required python packages for build and coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install 'urllib3==1.22' --force-reinstall
  # and then install WCPG wrapper
  - python setup.py  install

script:
    - pytest -k construct --cov=fixif -s

notifications:
email: false

after_success:
    # run coveralls for Python 3.6 under linux with Sollya and Slycot installed
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6"  && "$TRAVIS_OS_NAME" == "linux" ]]; then
          coveralls;
      fi
